### ISSUE TITLE
If anyone has this problem, ask for help.

### ISSUE THREAD

**Issue by henlyta** [EvoCargo/RaindropsOnWindshield#4]
Traceback (most recent call last):
  File "E:\Studying\trying\2024-1-9\RaindropsOnWindshield-main\raindrops_generator\raindrop\dropgenerator.py", line 12, in <module>
    from raindrop import Raindrop, make_bezier
  File "E:\Studying\trying\2024-1-9\RaindropsOnWindshield-main\raindrops_generator\raindrop\raindrop.py", line 6, in <module>
    import pyblur
  File "D:\Anaconda\Anaconda\envs\torch39\lib\site-packages\pyblur\__init__.py", line 5, in <module>
    from .PsfBlur import PsfBlur, PsfBlur_random
  File "D:\Anaconda\Anaconda\envs\torch39\lib\site-packages\pyblur\PsfBlur.py", line 11, in <module>
    psfDictionary = pickle.load(pklfile)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 410: ordinal not in range(128)

**Comment by XingyuLiu00** [comment]
PyBlur.py Line 11: from ' psfDictionary = pickle.load(pklfile) ' to ' psfDictionary = pickle.load(pklfile, encoding='bytes') '
